# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      wget https://download.racket-lang.org/installers/8.6/racket-8.6-x86_64-linux-cs.sh
      sudo sh racket-8.6-x86_64-linux-cs.sh --unix-style --dest /usr/
      raco pkg install --auto fmt racket-langserver

vscode:
  extensions:
    - evzen-wybitul.magic-racket
